///////////////////////////////////////////////////////////////////////////////////////////////////////////////
CREATE TABLE BATCH.JOB_EXEC_HISTORY
(
  JOB_SEQ              NUMERIC(19) PRIMARY KEY,
  JOB_ID               VARCHAR(500),
  IP                   VARCHAR(20),
  PID                  VARCHAR(30),
  JOB_TYPE			   VARCHAR(30),
  STATUS               VARCHAR(20),
  EXIT_MESSAGE         TEXT,
  LOG_FILES            VARCHAR(4000),
  ACTIVE_THREAD_COUNT  NUMERIC(4),
  CURRENT_CPU_USAGE    NUMERIC(5,2),
  TOTAL_CPU_USAGE      NUMERIC(5,2),
  FREE_MEMORY          NUMERIC(20),
  TOTAL_MEMORY         NUMERIC(20),
  CREATE_TIME          DATETIME,
  LAST_UPDATED         DATETIME
);

CREATE UNIQUE INDEX JOB_EXEC_HISTORY_PK ON BATCH.JOB_EXEC_HISTORY(JOB_SEQ);

CREATE INDEX JOB_EXEC_HISTORY_I1 ON BATCH.JOB_EXEC_HISTORY(JOB_ID, STATUS);

CREATE INDEX JOB_EXEC_HISTORY_I2 ON BATCH.JOB_EXEC_HISTORY(CREATE_TIME);

///////////////////////////////////////////////////////////////////////////////////////////////////////////////
CREATE TABLE BATCH.STEP_EXEC_HISTORY
(
  JOB_SEQ           NUMERIC(19)			NOT NULL,
  STEP_ID           VARCHAR(500)	NOT NULL,
  JOB_ID            VARCHAR(500),
  PID               VARCHAR(30),
  IP                VARCHAR(20),
  STATUS            VARCHAR(20),
  EXIT_MESSAGE      TEXT,
  LOG_FILES         VARCHAR(4000),
  ACTIVE_THREAD_COUNT  NUMERIC(4),
  CURRENT_CPU_USAGE    NUMERIC(5,2),
  TOTAL_CPU_USAGE      NUMERIC(5,2),
  FREE_MEMORY          NUMERIC(20),
  TOTAL_MEMORY         NUMERIC(20),
  CREATE_TIME       DATETIME,
  LAST_UPDATED      DATETIME
);

CREATE UNIQUE INDEX STEP_EXEC_HISTORY_PK ON BATCH.STEP_EXEC_HISTORY
(JOB_SEQ, STEP_ID);

///////////////////////////////////////////////////////////////////////////////////////////////////////////////
CREATE TABLE BATCH.RESOURCE_MANAGEMENT
(
  JOB_SEQ        NUMERIC(19)				NOT NULL,
  STEP_ID        VARCHAR(200)		NOT NULL,
  RESOURCE_NAME  VARCHAR(200)		NOT NULL,
  IO_TYPE        VARCHAR(10)		NOT NULL,
  STATUS         VARCHAR(10),
  JOB_ID         VARCHAR(200),
  TYPE           VARCHAR(10),
  TRANSACTED_COUNT  NUMERIC(38),
  CREATE_TIME    DATETIME,
  UPDATE_TIME    DATETIME
);

CREATE UNIQUE INDEX RESOURCE_MANAGEMENT_PK ON BATCH.RESOURCE_MANAGEMENT
(RESOURCE_NAME, JOB_SEQ, STEP_ID, IO_TYPE);

CREATE INDEX RESOURCE_MANAGEMENT_I1 ON BATCH.RESOURCE_MANAGEMENT
(JOB_SEQ, STEP_ID);

CREATE INDEX RESOURCE_MANAGEMENT_I2 ON BATCH.RESOURCE_MANAGEMENT
(RESOURCE_NAME, STATUS);

///////////////////////////////////////////////////////////////////////////////////////////////////////////////
CREATE TABLE BATCH.JOB_SEQ_TABLE
(
	JOB_SEQ NUMERIC(19) IDENTITY(1,1) PRIMARY KEY,
	TEMP VARCHAR(1)
);